export enum IconNames {
	ArrowBack = 'arrow_back',
	ArrowDownward = 'arrow_downward',
	ArrowForward = 'arrow_forward',
	ArrowUpward = 'arrow_upward',
	Cancel = 'cancel',
	Done = 'done',
	Equalizer = 'equalizer',
	Email = 'email',
	Event = 'event',
	Help = 'help',
	HighlightOff = 'highlight_off',
	Lightbulb = 'lightbulb',
	Lock = 'lock',
	Server = 'server',
	Settings = 'settings',
	Notifications = 'notifications',
	NotificationsNone = 'notifications_none',
	Power = 'power',
	Print = 'print',
	Visibility = 'visibility',
	Wifi = 'wifi'
}
