export enum IconNames {
  ArrowBack = 'arrow_back',
  ArrowDownward = 'arrow_downward',
  ArrowForward = 'arrow_forward',
  ArrowUpward = 'arrow_upward',
  Cancel = 'cancel',
  ChartLine = 'chart-line',
  Devices = 'cellphone-link',
  Done = 'done',
  Equalizer = 'equalizer',
  Email = 'email',
  Event = 'event',
  Help = 'help',
  Home = 'home',
  HighlightOff = 'highlight_off',
  Lightbulb = 'lightbulb',
  ListBulleted = 'list-bulleted',
  Lock = 'lock',
  Server = 'server',
  Settings = 'settings',
  Notifications = 'notifications',
  NotificationsNone = 'notifications_none',
  Power = 'power',
  Print = 'print',
  Update = 'update',
  Visibility = 'visibility',
  Wifi = 'wifi'
}
