export type IconNames = [
  'arrow_back',
  'arrow_downward',
  'arrow_forward',
  'arrow_upward',
  'cancel',
  'chart-line',
  'cellphone-link',
  'done',
  'equalizer',
  'email',
  'event',
  'help',
  'home',
  'highlight_off',
  'lightbulb',
  'list-bulleted',
  'lock',
  'server',
  'settings',
  'notifications',
  'notifications_none',
  'power',
  'print',
  'update',
  'visibility',
  'wifi'
]

export type IconName = IconNames[number]
